# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "./"
  # Default build command.
  command = "pnpm build"

[build.environment]
  # Optional: ensure consistent engines on Netlify
  NODE_VERSION = "20"
  PNPM_VERSION = "10.6.5"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/examples/viz.html"
  status = 200